local eventOptions = {
    "MAGGYHELPER_CH0_THEO",
    "MAGGYHELPER_CH0_ENDING",
    "MAGGYHELPER_MOD_CITY_END_1",
    "MAGGYHELPER_CH1_MOD_CITY_END",
    "MAGGYHELPER_CH2_CHARA_INTRO",
    "MAGGYHELPER_CH2_CHARA_MIRROR",
    "MAGGYHELPER_CHARA_TRAP",
    "MAGGYHELPER_CH2_CHARA_TRAP",
    "MAGGYHELPER_CALL_KIRBY",
    "MAGGYHELPER_CH2_CALL_KIRBY",
    "MAGGYHELPER_CH2_JOURNAL",
    "MAGGYHELPER_CH3_MEETUP",
    "MAGGYHELPER_CH3_FIRST_STEP",
    "MAGGYHELPER_MOD_CITY_END_2",
    "MAGGYHELPER_CH3_MOD_CITY_END",
    "MAGGYHELPER_CH4_ESCAPE",
    "MAGGYHELPER_CH4_CALL_MOM",
    "MAGGYHELPER_CH4_MIRROR",
    "MAGGYHELPER_CH4_CHARA_WARNING",
    "MAGGYHELPER_CH4_ENDING",
    "MAGGYHELPER_CH5_SEE_MADDY",
    "MAGGYHELPER_CH5_DIARY",
    "MAGGYHELPER_CH5_GUESTBOOK",
    "MAGGYHELPER_CH5_MEMO",
    "MAGGYHELPER_CH5_MADDY_PHONE",
    "MAGGYHELPER_CH5_ENDING",
    "MAGGYHELPER_CH5_MAGORLOR_ESCAPE",
    "MAGGYHELPER_CH5_OSHIRO_LOBBY",
    "MAGGYHELPER_CH5_OSHIRO_CLUTTER",
    "MAGGYHELPER_CH6_INTRO",
    "MAGGYHELPER_CH6_STRONGHOLD",
    "MAGGYHELPER_CH6_END",
    "MAGGYHELPER_CH7_ENTER",
    "MAGGYHELPER_CH7_INTRO",
    "MAGGYHELPER_CH7_SEE_MADDY_MIRROR",
    "MAGGYHELPER_CH7_GENOCIDE_MIRROR_PORTAL",
    "MAGGYHELPER_CH7_GENOCIDE_VISION_INTRO",
    "MAGGYHELPER_CH7_GENOCIDE_VISION_FINALES",
    "MAGGYHELPER_CH7_GENOCIDE_WAKEUP",
    "MAGGYHELPER_CH7_PRE_INGESTE",
    "MAGGYHELPER_CH7_SEE_MADDY",
    "MAGGYHELPER_CH7_FOUND_MADDY",
    "MAGGYHELPER_CH7_MIRROR_PORTAL",
    "MAGGYHELPER_CH7_DARKER",
    "MAGGYHELPER_CH8_PLAT",
    "MAGGYHELPER_CH8_REFLECTIONMOD",
    "MAGGYHELPER_CH8_THEO",
    "MAGGYHELPER_CH8_CHARABOSS_INTRO",
    "MAGGYHELPER_CH8_INTRO_CHARA_BOSS",
    "MAGGYHELPER_CH8_CHARA_BOSS_MID",
    "MAGGYHELPER_CH8_CHARA_BOSS_CENTER",
    "MAGGYHELPER_CH8_CHARA_BOSS_END",
    "MAGGYHELPER_CH8_END",
    "MAGGYHELPER_CH8_STAR_JUMP_END",
    "MAGGYHELPER_CH9_ARRIVIAL",
    "MAGGYHELPER_CH9_GOLDENFLOWER",
    "MAGGYHELPER_CH9_FAKE_SAVED",
    "MAGGYHELPER_CH9_CREDITS",
    "MAGGYHELPER_CH9_MESSAGE_END",
    "MAGGYHELPER_CH9_END",
    "MAGGYHELPER_CH10_INTRO",
    "MAGGYHELPER_CH10_FLOWEY_INTRO",
    "MAGGYHELPER_CH10_FLOWEY_INTRO_SCENE",
    "MAGGYHELPER_CH10 House",
    "MAGGYHELPER_CH10_HOUSE_INDOOR",
    "MAGGYHELPER_CH10_HOUSE_OUTDOOR",
    "MAGGYHELPER_CH10_PRE_BOSS",
    "MAGGYHELPER_CH10_POST_BOSS",
    "MAGGYHELPER_CH10_PIANO_START",
    "MAGGYHELPER_CH10_ROXUS_START",
    "MAGGYHELPER_CH10_SANS_RESTAURANT",
    "MAGGYHELPER_CH10_TITAN_TOWER_APPROACH",
    "MAGGYHELPER_CH10_TITAN_BOSS_BATTLE",
    "MAGGYHELPER_CH10_MADDY_BADDY_CHARA_INTRO",
    "MAGGYHELPER_CH11_INTRO",
    "MAGGYHELPER_CH11_TOWN",
    "MAGGYHELPER_CH11_MARLET_PRE_BOSS",
    "MAGGYHELPER_CH11_MARLET_BOSS_END",
    "MAGGYHELPER_CH11_BAR_ARRIVAL",
    "MAGGYHELPER_CH11_COWBOY_BAR_INTRO",
    "MAGGYHELPER_CH11_CINEMATIC_BAR",
    "MAGGYHELPER_CH11_MAGGY",
    "MAGGYHELPER_CH11_MAGGY_END",
    "MAGGYHELPER_CH11_COLLECTING_MINI_HEART_ENOUGH",
    "MAGGYHELPER_CH11_BOSS_INTRO",
    "MAGGYHELPER_CH11_BOSS_MID",
    "MAGGYHELPER_CH11_BOSS_OUTRO",
    "MAGGYHELPER_CH11_STARLO_AND_MARLET",
    "MAGGYHELPER_CH12_INTRO",
    "MAGGYHELPER_CH12_TITAN_TOWER",
    "MAGGYHELPER_CH12_TITAN_PRE_BOSS",
    "MAGGYHELPER_CH12_UNDYNE_REFUSED_TO_DIED",
    "MAGGYHELPER_CH12_TITAN_POST_BOSS",
    "MAGGYHELPER_CH12_END",
    "MAGGYHELPER_CH13_HOT_LAVA",
    "MAGGYHELPER_CH13_AXIS_INTRO",
    "MAGGYHELPER_CH13_WELL_PREPARED",
    "MAGGYHELPER_CH13_AXIS_PRE_BOSS",
    "MAGGYHELPER_CH13_AXIS_POST_BOSS",
    "MAGGYHELPER_CH13_END",
    "MAGGYHELPER_CH13_INTRO",
    "MAGGYHELPER_CH13_META_KNIGHT_ENCOUNTER",
    "MAGGYHELPER_CH13_AXIS_BOSS_BATTLE",
    "MAGGYHELPER_CH14_INTRO_CORE",
    "MAGGYHELPER_CH14_GIGA_AXIS_PRE_BOSS",
    "MAGGYHELPER_CH14_GIGA_AXIS_POST_BOSS",
    "MAGGYHELPER_CH14_ENTER_LAST_ELEVATOR",
    "MAGGYHELPER_CH14_INTRO",
    "MAGGYHELPER_CH14_HOLLOW_PROGRAMMER",
    "MAGGYHELPER_CH14_GIANT_AXIS_BATTLE",
    "MAGGYHELPER_CH15_EXIT_LAST_ELEVATOR",
    "MAGGYHELPER_CH15_ZANTAS_1",
    "MAGGYHELPER_CH15_ZANTAS_2",
    "MAGGYHELPER_CH15_JUDGEMENT",
    "MAGGYHELPER_CH15_INTRO_ROARING_TITAN",
    "MAGGYHELPER_CH15_BARRIER",
    "MAGGYHELPER_CH15_ROARING_TITAN_PRE_BOSS",
    "MAGGYHELPER_CH15_ROARING_TITAN_POST_BOSS",
    "MAGGYHELPER_CH15_FLOWEY_TRANSFORMATION",
    "MAGGYHELPER_CH15_MOUNTAIN_peak_ARRIVAL",
    "MAGGYHELPER_CH15_ROARING_TITAN_KING_BATTLE",
    "MAGGYHELPER_CH15_TITAN_COUNCIL_JUDGMENT",
    "MAGGYHELPER_CH16_ELS_INTRO",
    "MAGGYHELPER_CH16_ELS_FINALE",
    "MAGGYHELPER_CH16_ELS_OUTRO",
    "MAGGYHELPER_CH16_EXITED",
    "MAGGYHELPER_CH16_END",
    "MAGGYHELPER_CH16_EPILOUGE",
    "MAGGYHELPER_CH16_BARRIER_BREAKS",
    "MAGGYHELPER_CH16_CORRUPTED_REALITY_INTRO",
    "MAGGYHELPER_CH16_LOST_SOULS_UNITE",
    "MAGGYHELPER_CH16_SAVE_FILE_BATTLE",
    "MAGGYHELPER_CH17_WELCOMEHOME",
    "MAGGYHELPER_CH17_EPILOUGE",
    "MAGGYHELPER_CH17_CREDITS",
    "MAGGYHELPER_CH17_ENDING_MOD",
    "MAGGYHELPER_CH18_OUTRO",
    "MAGGYHELPER_CH19_ANOTHER_DIMENSION_INTRO",
    "MAGGYHELPER_CH19_GOTO_THE_FUTURE",
    "MAGGYHELPER_CH19_GOTO_THE_PAST",
    "MAGGYHELPER_CH19_CHARA_HELP",
    "MAGGYHELPER_CH19_HUB_SECOND_INTRO",
    "MAGGYHELPER_CH19_HUB_SECOND_INTRO_TRIGGER",
    "MAGGYHELPER_CH19_LOOP",
    "MAGGYHELPER_CH19_BIG_FINAL_ROOM",
    "MAGGYHELPER_CH19_FREE_BIRD",
    "MAGGYHELPER_CH19_KILL_THE_BIRD",
    "MAGGYHELPER_CH19_MISS_THE_BIRD",
    "MAGGYHELPER_CH19_GRAVESTONE",
    "MAGGYHELPER_CH19_FINAL_LAUNCH",
    "MAGGYHELPER_CH19_SOULS_DISCARDED",
    "MAGGYHELPER_CH19_BEYOND_THE_VOID",
    "MAGGYHELPER_CH19_MEMORIES_OF_THE_PAST",
    "MAGGYHELPER_CH19_ELS_BREAKS_FREE",
    "MAGGYHELPER_CH19_BROKEN_STAR_WARRIOR",
    "MAGGYHELPER_CH19_EDGE_OF_UNIVERSE",
    "MAGGYHELPER_CH20_BIRD_GUIDANCE_INTRO",
    "MAGGYHELPER_CH20_INTRO",
    "MAGGYHELPER_CH20_FAKE_MADELINE_AND_BADELINE",
    "MAGGYHELPER_CH20_TESS_FAKE_PRE_BOSS",
    "MAGGYHELPER_CH20_TESS_FAKE_POST_BOSS",
    "MAGGYHELPER_CH20_NOTHINESS",
    "MAGGYHELPER_CH20_ASRIEL_GOD_BOSS_IDENTITY_REVEAL",
    "MAGGYHELPER_CH20_ASRIEL_GOD_BOSS_IDENTITY_REVEAL_TRIGGER",
    "MAGGYHELPER_CH20_TESS_PRE_BOSS_FOR_REAL",
    "MAGGYHELPER_CH20_SAVED",
    "MAGGYHELPER_CH21_SAVED",
    "MAGGYHELPER_CH21_SAVED",
    "MAGGYHELPER_CH20_SAVED",
    "MAGGYHELPER_CH20_ENDING",
    "MAGGYHELPER_CH21_ENDING",
    "MAGGYHELPER_CH21_ENDING",
    "MAGGYHELPER_CH20_ENDING",
    "MAGGYHELPER_CH20_ASRIEL_ANGEL_OF_DEATH_BOSS_INTRO",
    "MAGGYHELPER_CH20_BOSS_MID",
    "MAGGYHELPER_CH20_BOSS_END",
    "MAGGYHELPER_CH20_ASRIEL_BOSS_END",
    "MAGGYHELPER_CH20_ELSFINALBOSS",
    "MAGGYHELPER_CH21_ELSFINALBOSS",
    "MAGGYHELPER_CH21_ELSFINALBOSS",
    "MAGGYHELPER_CH20_FINAL_BOSS_DEFEAT",
    "MAGGYHELPER_CH20_RAINBOW_BLOSSOM_TREE",
    "MAGGYHELPER_CH20_FAREWELL",
    "MAGGYHELPER_CH21_FAREWELL",
    "MAGGYHELPER_CH21_FAREWELL",
    "MAGGYHELPER_CH20_RESTORATION_AND_FAREWELL",
    "MAGGYHELPER_CH20_LATER",
    "MAGGYHELPER_CH21_LATER",
    "MAGGYHELPER_CH21_LATER",
    "MAGGYHELPER_CH20_END_LATER",
    "MAGGYHELPER_CH20_END_CINEMATIC",
    "MAGGYHELPER_CH20_CAST",
    }

local cutsceneEventDispatcher = {}

cutsceneEventDispatcher.name = "MaggyHelper/CutsceneEventDispatcher"
cutsceneEventDispatcher.canResize = {true, true}
cutsceneEventDispatcher.placements = {
    {
        name = "default",
        data = {
            x = 0,
            y = 0,
            width = 16,
            height = 16,
            event = ""
        }
    },
    {
        name = "chapter_intro",
        data = {
            x = 0,
            y = 0,
            width = 24,
            height = 16,
            event = "ch10_intro"
        }
    },
    {
        name = "boss_intro",
        data = {
            x = 0,
            y = 0,
            width = 32,
            height = 16,
            event = "ch11_boss_intro"
        }
    },
    {
        name = "boss_mid",
        data = {
            x = 0,
            y = 0,
            width = 16,
            height = 16,
            event = "ch20_boss_mid"
        }
    },
    {
        name = "asriel_angel_boss_intro",
        data = {
            x = 0,
            y = 0,
            width = 32,
            height = 16,
            event = "ch20_asriel_angel_of_death_boss_intro"
        }
    },
    {
        name = "boss_end",
        data = {
            x = 0,
            y = 0,
            width = 24,
            height = 16,
            event = "ch20_boss_end"
        }
    },
    {
        name = "ending",
        data = {
            x = 0,
            y = 0,
            width = 32,
            height = 16,
            event = "ch20_ending"
        }
    },
    {
        name = "credits",
        data = {
            x = 0,
            y = 0,
            width = 32,
            height = 16,
            event = "ch21_epilogue_credits"
        }
    }
}

cutsceneEventDispatcher.fieldInformation = {
    event = {
        fieldType = "string",
        editable = true,
        options = eventOptions
    }
}

cutsceneEventDispatcher.fieldOrder = {
    "x",
    "y",
    "width",
    "height",
    "event"
}

function cutsceneEventDispatcher.color(room, entity)
    if entity.event == nil or entity.event == "" then
        return {0.85, 0.35, 0.35, 0.8}
    end

    return {0.35, 0.8, 0.95, 0.8}
end

function cutsceneEventDispatcher.sprite(room, entity)
    local width = entity.width or 16
    local height = entity.height or 16

    return {
        {
            texture = "ahorn/entityTrigger",
            x = entity.x,
            y = entity.y,
            scaleX = width / 8,
            scaleY = height / 8,
            color = cutsceneEventDispatcher.color(room, entity)
        }
    }
end

function cutsceneEventDispatcher.selection(room, entity)
    local width = entity.width or 16
    local height = entity.height or 16

    return {
        entity.x,
        entity.y,
        width,
        height
    }
end

return cutsceneEventDispatcher